web:
  image: wordpress
  links:
  - mysql
  environment:
  - WORDPRESS_DB_PASSWORD=root
  ports:
  - "5500:80"
mysql:
  image: mysql:5.7
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=unvoternews
  ports:
  - "3306:3306"